# Generated by Django 4.0 on 2022-12-17 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='prodcut',
            new_name='product',
        ),
    ]
